# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e280fc1b34732273fa126c64388b9cd069218aa51e68b4641633af3e1ae81d77851ae7f66bb19f99bfb073f01880f60ea7689bdcb5d760844188326559ed6041

test:
  secret_key_base: 7ab2c08490b5602ce654df85e3626f61d5613cdfa2f707fbdd04c906231eccb5e36a44a59a5756131121d63b0c0fe4951620095d8b9ef3cd2b28e636a7466807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
